repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.452
    hooks:
    - id: checkov

  - repo: https://github.com/tenable/terrascan
    rev: v1.19.9
    hooks:
    - id: terraform-pre-commit
      args: [--iac-type, terraform]
      files: ^(.*)$
      pass_filenames: false

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
    - id: terraform_trivy
    - id: terraform_docs
      args:
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
